export { default as ProgrammingLanguageManager } from './App';
export { configureCors } from './config/cors';
export type { CorsConfig } from './config/cors';
export * from './components/LanguageCard/LanguageCard';
export * from './components/Forms/LanguageForm';
export * from './components/Search/SearchBar';
export * from './components/Spaces/SpaceSelector';
export * from './components/Spaces/InnovationSpace';
export * from './components/Spaces/TechnologySpace';
export * from './components/Layout/Header';
export * from './components/Modal/Modal';
export * from './components/ui/Tabs';
export * from './types/language';
export * from './types/spaces';
export * from './data/languages';
export * from './data/spaces';
export * from './hooks/useLocalStorage';